INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category ( name, created_At) VALUES ('ELETRODOMESTICOS', NOW());
INSERT INTO tb_category ( name, created_At ) VALUES ('ELETRONICOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BRINQUEDOS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('ELETRODOMESTICOS', NOW());